import 'dart:convert';
import 'dart:io';

import 'package:nodus/nodus_migrations.dart';
import 'package:nodus/src/configuration.dart';
import 'package:nodus/src/tool/migration_generator.dart';
import 'package:test/test.dart';

void main() {
  group('generation options', () {
    test('explicit generated acknowledgement satisfies semantic review', () {
      const plan = NodusMigrationPlan<GeneratedDatabase>.acknowledgeGenerated();

      expect(plan.runsGeneratedSteps, isTrue);
      expect(plan.handlesManualChanges, isTrue);
    });

    test('parse migration modes and reject ambiguous input', () {
      final options = parseGenerationOptions([
        '--bootstrap-supabase-migration',
        'initial_schema',
        '--overwrite-bootstrap',
      ]);

      expect(options.bootstrapSupabaseMigration, 'initial_schema');
      expect(options.overwriteBootstrap, isTrue);
      expect(parseGenerationOptions(['--help']).showHelp, isTrue);
      expect(
        parseGenerationOptions(['--migration', 'next_schema']).migration,
        'next_schema',
      );
      expect(
        parseGenerationOptions([
          '--defer-supabase-composition',
        ]).deferSupabaseComposition,
        isTrue,
      );
      expect(
        parseGenerationOptions(['--reset-drift-baseline']).resetDriftBaseline,
        isTrue,
      );
      expect(
        () => parseGenerationOptions([
          '--migration',
          'generic',
          '--supabase-migration',
          'next_schema',
        ]),
        throwsA(isA<NodusToolUsageException>()),
      );
      expect(
        () => parseGenerationOptions([
          '--supabase-migration',
          'next_schema',
          '--bootstrap-supabase-migration',
          'initial_schema',
        ]),
        throwsA(isA<NodusToolUsageException>()),
      );
      expect(
        () => parseGenerationOptions([
          '--defer-supabase-composition',
          '--supabase-migration',
          'next_schema',
        ]),
        throwsA(isA<NodusToolUsageException>()),
      );
      expect(
        () => parseGenerationOptions(['--supabase-migration', 'Not-Snake']),
        throwsA(isA<NodusToolUsageException>()),
      );
      expect(
        () => parseGenerationOptions([
          '--supabase-migration',
          'first',
          '--supabase-migration',
          'second',
        ]),
        throwsA(isA<NodusToolUsageException>()),
      );
    });

    test('parses semantic inventory modes', () {
      expect(parseInventoryOptions([]).mode, NodusInventoryMode.print);
      expect(parseInventoryOptions(['--write']).mode, NodusInventoryMode.write);
      expect(parseInventoryOptions(['--check']).mode, NodusInventoryMode.check);
      expect(parseInventoryOptions(['--json']).mode, NodusInventoryMode.json);
      expect(parseInventoryOptions(['--help']).showHelp, isTrue);
      expect(
        () => parseInventoryOptions(['--write', '--json']),
        throwsA(isA<NodusToolUsageException>()),
      );
    });
  });

  group('Drift migration generation', () {
    test('unchanged output is not rewritten', () {
      final root = Directory.systemTemp.createTempSync('nodus_write_');
      addTearDown(() => root.deleteSync(recursive: true));
      final output = File('${root.path}/generated.dart')
        ..writeAsStringSync('stable\n');
      final modified = output.lastModifiedSync();

      expect(writeIfChanged(output, 'stable\n'), isFalse);
      expect(output.lastModifiedSync(), modified);
    });

    test('reset removes only generated local Drift history', () {
      final fixture = _Fixture(createPackage: true);
      addTearDown(fixture.dispose);
      fixture.writeSchema(1, [_column('id')]);
      fixture.writeSchema(2, [_column('id'), _column('title')]);
      final steps = fixture.file('lib/src/generated/nodus.runtime.g.steps.dart')
        ..createSync(recursive: true)
        ..writeAsStringSync('// generated steps\n');
      final generated = fixture.file('test/drift/generated/schema_v2.dart')
        ..createSync(recursive: true)
        ..writeAsStringSync('// GENERATED BY drift_dev, DO NOT MODIFY.\n');
      final preserved = fixture.file('test/drift/generated/manual.dart')
        ..writeAsStringSync('// authored\n');
      final lockFile = fixture.file('nodus.lock')
        ..writeAsStringSync(
          const NodusLock(
            packageName: 'fixture',
            graphName: 'Fixture',
            schemaVersion: 4,
            schemaFingerprint:
                'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
            targets: ['supabase'],
            defaultTarget: 'supabase',
          ).encode(),
        );

      fixture.generator().resetDriftBaseline();

      expect(fixture.schema.listSync(), isEmpty);
      expect(steps.existsSync(), isFalse);
      expect(generated.existsSync(), isFalse);
      expect(preserved.existsSync(), isTrue);
      expect(NodusLock.decode(lockFile.readAsStringSync()).schemaVersion, 1);
    });

    test('infers the single schema and steps locations', () {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      fixture.writeSchema(1, [_column('id')]);
      final steps = fixture.file('lib/src/generated/nodus.runtime.g.steps.dart')
        ..createSync(recursive: true)
        ..writeAsStringSync('// steps');
      final generator = fixture.generator();

      expect(generator.inferDriftSchemaDirectory().path, fixture.schema.path);
      expect(generator.inferDriftStepsFile().path, steps.path);
    });

    test('ignores unstable internal index ownership ids', () {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      final oldFile = fixture.writeSchema(1, [_column('id')], indexOwner: 1);
      final newFile = fixture.writeSchema(2, [_column('id')], indexOwner: 9);

      final proposal = fixture.generator().migrationStatements(
        oldFile,
        newFile,
      );

      expect(proposal.statements, isEmpty);
      expect(proposal.requiresManualChanges, isFalse);
    });

    test('generates safe additions and flags required additions', () {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      final oldFile = fixture.writeSchema(1, [_column('id')]);
      final nullable = fixture.writeSchema(2, [
        _column('id'),
        _column('display_name', nullable: true),
      ]);
      final required = fixture.writeSchema(3, [
        _column('id'),
        _column('display_name'),
      ]);
      final generator = fixture.generator();

      final safe = generator.migrationStatements(oldFile, nullable);
      expect(safe.requiresManualChanges, isFalse);
      expect(safe.statements.join('\n'), contains('schema.notes.displayName'));

      final unsafe = generator.migrationStatements(oldFile, required);
      expect(unsafe.requiresManualChanges, isTrue);
      expect(unsafe.statements, isEmpty);
    });

    test('emits an acknowledged rebuild for changed table constraints', () {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      final oldFile = fixture.writeSchema(1, [_column('id')]);
      final newFile = fixture.writeSchema(
        2,
        [_column('id')],
        constraints: const ['check (id <> \'\')'],
      );

      final proposal = fixture.generator().migrationStatements(
        oldFile,
        newFile,
      );

      expect(proposal.requiresManualChanges, isTrue);
      expect(proposal.statements, [
        'await migrator.alterTable(TableMigration(schema.notes));',
      ]);
    });

    test('restores collision-free getters in Drift migration shapes', () {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      fixture.writeSchema(1, [_column('id')]);
      fixture.writeSchema(2, [
        _column('id'),
        _column('text', getterName: 'textColumn'),
      ]);
      final steps = fixture.file('lib/src/generated/nodus.runtime.g.steps.dart')
        ..createSync(recursive: true)
        ..writeAsStringSync('''
late final Shape1 notes = Shape1(
  source: i0.VersionedTable(
    entityName: 'notes',
  ),
);

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get text =>
      columnsByName['text']! as i1.GeneratedColumn<String>;
}
''');

      fixture.generator().normalizeDriftStepsAccessors();

      final output = steps.readAsStringSync();
      expect(output, contains('get textColumn =>'));
      expect(output, isNot(contains('get text =>')));
      expect(output, contains('get id =>'));
    });

    test('normalizes Drift migration-test accessors without renaming SQL', () {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      fixture.writeSchema(1, [
        _column('id'),
        _column('text', getterName: 'textColumn'),
      ]);
      fixture.writeSchema(2, [
        _column('id'),
        _column('text', getterName: 'textColumn'),
      ]);
      File generated(int version) =>
          fixture.file('test/drift/application/generated/schema_v$version.dart')
            ..createSync(recursive: true)
            ..writeAsStringSync('''
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
class Notes extends Table with TableInfo {
  late final GeneratedColumn<String> text = GeneratedColumn<String>(
    'text',
    aliasedName,
    false,
  );
  @override
  List<GeneratedColumn> get \$columns => [text];
  @override
  Set<GeneratedColumn> get \$primaryKey => {text};
  static const String \$name = 'notes';
  NotesData map(Map<String, dynamic> data) => NotesData(
    text: data['text'] as String,
  );
}
''');
      final historical = generated(1);
      final current = generated(2);

      fixture.generator().normalizeDriftTestSchemaAccessors();

      for (final schema in [historical, current]) {
        final output = schema.readAsStringSync();
        expect(output, contains('GeneratedColumn<String> textColumn ='));
        expect(output, contains(r'get $columns => [textColumn]'));
        expect(output, contains(r'get $primaryKey => {textColumn}'));
        expect(output, contains("static const String \$name = 'notes'"));
        expect(output, contains("text: data['text'] as String"));
      }
    });

    test('removes the no-op Drift data migration template', () {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      final migrationTest =
          fixture.file('test/drift/application/migration_test.dart')
            ..createSync(recursive: true)
            ..writeAsStringSync('''
import 'generated/schema.dart';
import 'package:fixture/src/generated/nodus.runtime.g.dart';
import 'generated/schema_v1.dart' as v1;
import 'generated/schema_v2.dart' as v2;

void main() {
  test('generated migration matrix', () {
    final schema = verifier.schemaAt(1);
    final db = FixtureDatabase(schema.newConnection());
  });

  // The following template shows how to write tests ensuring your migrations
  // preserve existing data.
  // Placeholder data setup
  test('migration from v1 to v2 does not corrupt data', () {});
}
''');

      fixture.generator().normalizeDriftMigrationTests();

      final output = migrationTest.readAsStringSync();
      expect(output, contains("import 'generated/schema.dart';"));
      expect(output, contains("test('generated migration matrix'"));
      expect(output, contains('nodus.migrations.g.dart'));
      expect(output, contains('nodusMigrationStrategy<FixtureDatabase>'));
      expect(output, contains('FixtureMetadata.definition.syncTargets'));
      expect(output, isNot(contains('schema_v1.dart')));
      expect(output, isNot(contains('schema_v2.dart')));
      expect(output, isNot(contains('Placeholder data setup')));
      expect(output.trimRight(), endsWith('}'));
    });

    test('replaces changed indexes without requiring application policy', () {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      final oldFile = fixture.writeSchema(
        1,
        [_column('id')],
        indexOwner: 0,
        indexSql: 'create unique index notes_id_idx on notes(id)',
      );
      final newFile = fixture.writeSchema(
        2,
        [_column('id')],
        indexOwner: 1,
        indexSql: 'create index notes_id_idx on notes(id, rowid)',
      );

      final proposal = fixture.generator().migrationStatements(
        oldFile,
        newFile,
      );

      expect(proposal.requiresManualChanges, isFalse);
      expect(proposal.statements, [
        'await migrator.drop(schema.notesIdIdx);',
        'await migrator.create(schema.notesIdIdx);',
      ]);
    });

    test('emits generic typed plans and guards unsafe transitions', () {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      fixture.writeSchema(1, [_column('id')]);
      fixture.writeSchema(2, [_column('id'), _column('label')]);
      fixture.file('lib/src/generated/nodus.runtime.g.steps.dart')
        ..createSync(recursive: true)
        ..writeAsStringSync('// steps');

      fixture.generator().emitDriftMigrations();

      final output = fixture
          .file('lib/src/generated/nodus.migrations.g.dart')
          .readAsStringSync();
      expect(output, contains('nodusMigrationStrategy'));
      expect(
        output,
        contains('required Iterable<SyncTargetId> initialPullTargets'),
      );
      expect(output, contains('(sync_target, cursor) values (?, 0)'));
      expect(output, isNot(contains('(id, cursor)')));
      expect(output, contains('NodusMigrationHooks'));
      expect(output, contains('<D extends GeneratedDatabase>'));
      expect(output, contains('applyNodusMigrationPlan<D>('));
      expect(output, contains('plan.handlesManualChanges'));
      expect(
        output,
        contains("import './nodus.runtime.g.steps.dart' as steps;"),
      );
      expect(output, isNot(contains('WorkItems')));
    });
  });

  group('Supabase migration generation', () {
    test('composes ordered sources, generated schema, and extensions', () {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      fixture.file('supabase/schema_sources/20_legacy_views.sql')
        ..createSync(recursive: true)
        ..writeAsStringSync('create view public.legacy_view as select 1;\n');
      fixture.file('supabase/schema_sources/10_legacy_tables.sql')
        ..createSync(recursive: true)
        ..writeAsStringSync('create table public.legacy(id uuid);\n');
      fixture.file('supabase/nodus/schema.sql')
        ..createSync(recursive: true)
        ..writeAsStringSync('create table public.example(id uuid);\n');
      fixture.file('supabase/schema_extensions/20_views.sql')
        ..createSync(recursive: true)
        ..writeAsStringSync('create view public.example_view as select 1;\n');
      fixture.file('supabase/schema_extensions/10_functions.sql')
        ..createSync(recursive: true)
        ..writeAsStringSync('create function public.example() returns int;\n');

      fixture.generator().synchronizeSupabaseSchema();

      final schema = fixture
          .file('supabase/schemas/public.sql')
          .readAsStringSync();
      expect(schema, startsWith('-- Schema source: 10_legacy_tables.sql'));
      expect(
        schema.indexOf('10_legacy_tables.sql'),
        lessThan(schema.indexOf('20_legacy_views.sql')),
      );
      expect(
        schema.indexOf('20_legacy_views.sql'),
        lessThan(schema.indexOf('create table public.example')),
      );
      expect(
        schema.indexOf('10_functions.sql'),
        lessThan(schema.indexOf('20_views.sql')),
      );
    });

    test('schema synchronization requires generated entity SQL', () {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);

      expect(
        fixture.generator().synchronizeSupabaseSchema,
        throwsA(isA<NodusToolUsageException>()),
      );
    });

    test('appends a named manual fragment to a declarative diff', () async {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      fixture.file('supabase/manual_migrations/add_index.sql')
        ..createSync(recursive: true)
        ..writeAsStringSync('select rebuild_cache();\n');
      final output = fixture.file(
        'supabase/migrations/20260711000000_add_index.sql',
      );
      final generator = fixture.generator(
        runCommand: (executable, arguments, {required workingDirectory}) async {
          output
            ..createSync(recursive: true)
            ..writeAsStringSync('create index example_idx on example(id);\n');
        },
      );

      await generator.generateSupabaseMigration('add_index');

      final source = output.readAsStringSync();
      expect(source, contains('create index example_idx'));
      expect(source, contains('Reviewed manual migration extension'));
      expect(source, contains('select rebuild_cache();'));
    });

    test('uses explicit replacement without running a diff', () async {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      fixture.file('supabase/manual_migrations/rebuild.replace.sql')
        ..createSync(recursive: true)
        ..writeAsStringSync('alter table example rename column a to b;\n');
      var ranCommand = false;
      final generator = fixture.generator(
        runCommand: (executable, arguments, {required workingDirectory}) async {
          ranCommand = true;
        },
      );

      await generator.generateSupabaseMigration('rebuild');

      expect(ranCommand, isFalse);
      final output = fixture.namedMigration('rebuild').readAsStringSync();
      expect(output, contains('Reviewed manual replacement'));
      expect(output, contains('rename column a to b'));
    });

    test('creates a manual-only migration when the diff is empty', () async {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      fixture.file('supabase/manual_migrations/backfill.sql')
        ..createSync(recursive: true)
        ..writeAsStringSync('update example set ready = true;\n');
      final generator = fixture.generator(
        runCommand:
            (executable, arguments, {required workingDirectory}) async {},
      );

      await generator.generateSupabaseMigration('backfill');

      final output = fixture.namedMigration('backfill').readAsStringSync();
      expect(output, contains('without a declarative schema diff'));
      expect(output, contains('set ready = true'));
    });

    test('bootstrap requires explicit overwrite', () {
      final fixture = _Fixture();
      addTearDown(fixture.dispose);
      final schema = fixture.file('supabase/schemas/public.sql')
        ..createSync(recursive: true)
        ..writeAsStringSync('create table example(id text);\n');
      final generator = fixture.generator();

      generator.bootstrapSupabaseMigration('initial', overwrite: false);
      expect(
        () => generator.bootstrapSupabaseMigration('initial', overwrite: false),
        throwsA(isA<NodusToolUsageException>()),
      );
      schema.writeAsStringSync('create table example(id integer);\n');
      generator.bootstrapSupabaseMigration('initial', overwrite: true);

      expect(
        fixture.namedMigration('initial').readAsStringSync(),
        contains('id integer'),
      );
    });
  });

  test('orchestration runs inferred generators before formatting', () async {
    final fixture = _Fixture(createPackage: true);
    addTearDown(fixture.dispose);
    fixture.writeSchema(1, [_column('id')]);
    fixture.file('supabase/nodus/schema.sql')
      ..createSync(recursive: true)
      ..writeAsStringSync('create table public.example(id uuid);\n');
    final commands = <String>[];
    final generator = fixture.generator(
      runCommand: (executable, arguments, {required workingDirectory}) async {
        commands.add('$executable ${arguments.join(' ')}');
      },
    );

    await generator.generate(const NodusGenerationOptions());

    expect(commands, [
      'dart run build_runner build',
      'dart run drift_dev make-migrations',
      'dart format lib',
    ]);
  });

  test('greenfield orchestration recreates the Drift test schema', () async {
    final fixture = _Fixture(createPackage: true);
    addTearDown(fixture.dispose);
    fixture.writeSchema(4, [_column('id')]);
    fixture.file('supabase/nodus/schema.sql')
      ..createSync(recursive: true)
      ..writeAsStringSync('create table public.example(id uuid);\n');
    final commands = <String>[];
    final generator = fixture.generator(
      runCommand: (executable, arguments, {required workingDirectory}) async {
        commands.add('$executable ${arguments.join(' ')}');
        if (arguments.join(' ') == 'run drift_dev make-migrations') {
          fixture.writeSchema(1, [_column('id')]);
        }
      },
    );

    await generator.generate(
      const NodusGenerationOptions(resetDriftBaseline: true),
    );

    expect(commands, [
      'dart run build_runner build',
      'dart run build_runner build',
      'dart run drift_dev make-migrations',
      'dart run drift_dev schema generate '
          'drift_schemas/application test/drift/application/generated',
      'dart format lib',
    ]);
  });

  test(
    'fast generation runs only compile-complete application outputs',
    () async {
      final fixture = _Fixture(createPackage: true);
      addTearDown(fixture.dispose);
      final commands = <String>[];
      final generator = fixture.generator(
        runCommand: (executable, arguments, {required workingDirectory}) async {
          commands.add('$executable ${arguments.join(' ')}');
        },
      );

      await generator.generateFast();

      expect(commands, hasLength(1));
      expect(commands.single, startsWith('dart run build_runner build'));
      expect(
        commands.single,
        contains('--build-filter=lib/src/generated/nodus.runtime.g.drift.dart'),
      );
      expect(commands.single, isNot(contains('make-migrations')));
    },
  );

  test('explain returns resolved human and JSON entity reports', () async {
    final fixture = _Fixture(createPackage: true);
    addTearDown(fixture.dispose);
    fixture.file('lib/src/generated/nodus.explain.g.json')
      ..createSync(recursive: true)
      ..writeAsStringSync(
        jsonEncode({
          'graph': 'Fixture',
          'schemaVersion': 1,
          'targets': ['supabase'],
          'entities': [
            {
              'name': 'Note',
              'table': 'notes',
              'source': 'package:fixture/note.dart',
              'ownership': 'separate',
              'cardinality': 'unbounded',
              'sync': {'mode': 'replicated', 'target': 'supabase'},
              'capabilities': {'archivable': true},
              'fields': [
                {
                  'name': 'title',
                  'type': 'String',
                  'column': 'title',
                  'source': 'entity declaration',
                },
              ],
            },
          ],
        }),
      );
    final generator = fixture.generator(
      runCommand: (_, _, {required workingDirectory}) async {},
    );

    expect(await generator.explain(entity: 'Note'), contains('Note -> notes'));
    expect(
      jsonDecode(await generator.explain(entity: 'Note', json: true)),
      containsPair('name', 'Note'),
    );
  });

  test(
    'semantic inventory write and check use the production scanner',
    () async {
      final fixture = _Fixture(createPackage: true);
      addTearDown(fixture.dispose);
      fixture.file('lib/src/generated/nodus.explain.g.json')
        ..createSync(recursive: true)
        ..writeAsStringSync(
          jsonEncode({
            'graph': 'Fixture',
            'schemaVersion': 1,
            'targets': ['supabase'],
            'entities': [
              {
                'name': 'Note',
                'table': 'notes',
                'source': 'package:fixture/note.dart',
                'ownership': 'separate',
                'cardinality': 'unbounded',
                'sync': {'mode': 'replicated', 'target': 'supabase'},
                'capabilities': <String, Object?>{},
                'fields': <Object?>[],
                'indexes': <Object?>[],
                'actions': <Object?>[],
                'generatedApi': {
                  'set': 'NoteSet',
                  'setAccessor': 'notes',
                  'list': 'NoteList',
                  'draft': 'NoteMutationDraft',
                  'create': true,
                },
              },
            ],
          }),
        );
      final source = fixture.file('lib/note.dart')
        ..writeAsStringSync('abstract class Note {}\n');
      final collateral = fixture.file('lib/provider.g.dart')
        ..writeAsStringSync('// stable generated output\n');
      final newlyGenerated = fixture.file('lib/provider.freezed.dart');
      final commands = <String>[];
      final generator = fixture.generator(
        runCommand: (executable, arguments, {required workingDirectory}) async {
          commands.add('$executable ${arguments.join(' ')}');
          collateral.writeAsStringSync('// transient build output\n');
          newlyGenerated.writeAsStringSync('// transient new output\n');
        },
      );

      await generator.inventory(
        const NodusInventoryOptions(mode: NodusInventoryMode.write),
      );
      await generator.inventory(
        const NodusInventoryOptions(mode: NodusInventoryMode.check),
      );

      source.writeAsStringSync(
        'abstract class Note {}\n'
        'Object stale() => NoteList.query(graph, pageSize: 1);\n',
      );
      await expectLater(
        generator.inventory(
          const NodusInventoryOptions(mode: NodusInventoryMode.check),
        ),
        throwsA(
          isA<NodusToolUsageException>().having(
            (error) => error.message,
            'message',
            contains('inventory is stale'),
          ),
        ),
      );
      expect(commands, everyElement('dart run build_runner build'));
      expect(collateral.readAsStringSync(), '// stable generated output\n');
      expect(newlyGenerated.existsSync(), isFalse);
    },
  );

  test(
    'deferred orchestration preserves the canonical Supabase schema',
    () async {
      final fixture = _Fixture(createPackage: true);
      addTearDown(fixture.dispose);
      fixture.writeSchema(1, [_column('id')]);
      fixture.file('supabase/nodus/schema.sql')
        ..createSync(recursive: true)
        ..writeAsStringSync('create table public.generated(id uuid);\n');
      final canonical = fixture.file('supabase/schemas/public.sql')
        ..createSync(recursive: true)
        ..writeAsStringSync('create table public.legacy(id uuid);\n');
      final generator = fixture.generator(
        runCommand: (_, _, {required workingDirectory}) async {},
      );

      await generator.generate(
        const NodusGenerationOptions(deferSupabaseComposition: true),
      );

      expect(
        canonical.readAsStringSync(),
        'create table public.legacy(id uuid);\n',
      );
    },
  );
}

Map<String, Object?> _column(
  String name, {
  bool nullable = false,
  String? defaultValue,
  String? getterName,
}) => {
  'name': name,
  'getter_name': getterName ?? _camelCase(name),
  'moor_type': 'string',
  'nullable': nullable,
  'customConstraints': null,
  'default_dart': defaultValue,
  'default_client_dart': null,
  'dsl_features': <Object?>[],
};

String _camelCase(String source) {
  final parts = source.split('_');
  return parts.first +
      parts
          .skip(1)
          .map((part) => '${part[0].toUpperCase()}${part.substring(1)}')
          .join();
}

final class _Fixture {
  _Fixture({bool createPackage = false})
    : root = Directory.systemTemp.createTempSync('nodus_migrations_') {
    schema.createSync(recursive: true);
    if (createPackage) {
      file('pubspec.yaml').writeAsStringSync('name: fixture\n');
      Directory('${root.path}/lib').createSync();
    }
  }

  final Directory root;

  Directory get schema => Directory('${root.path}/drift_schemas/application');

  File file(String relative) => File('${root.path}/$relative');

  File writeSchema(
    int version,
    List<Map<String, Object?>> columns, {
    int? indexOwner,
    String indexSql = 'create index notes_id_idx on notes(id)',
    List<Object?> constraints = const [],
  }) {
    final entities = <Object?>[
      {
        'type': 'table',
        'data': {
          'name': 'notes',
          'columns': columns,
          'constraints': constraints,
        },
      },
      if (indexOwner != null)
        {
          'type': 'index',
          'data': {'name': 'notes_id_idx', 'on': indexOwner, 'sql': indexSql},
        },
    ];
    final output = File('${schema.path}/drift_schema_v$version.json');
    output.writeAsStringSync(jsonEncode({'entities': entities}));
    return output;
  }

  NodusGenerator generator({CommandRunner? runCommand}) => NodusGenerator(
    root: root,
    runCommand: runCommand,
    nowUtc: () => DateTime.utc(2026, 7, 11),
    report: (_) {},
    warn: (_) {},
  );

  File namedMigration(String name) =>
      Directory('${root.path}/supabase/migrations')
          .listSync()
          .whereType<File>()
          .singleWhere((file) => file.path.endsWith('_$name.sql'));

  void dispose() => root.deleteSync(recursive: true);
}
