import 'dart:convert';
import 'dart:io';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';
import 'package:analyzer/source/line_info.dart';
import 'package:path/path.dart' as path;

const nodusConformanceInventoryPath = 'doc/nodus_conformance_inventory.md';

final class ConformanceRule {
  const ConformanceRule({
    required this.id,
    required this.title,
    required this.replacement,
  });

  final String id;
  final String title;
  final String replacement;
}

const nodusConformanceRules = <ConformanceRule>[
  ConformanceRule(
    id: 'exact-one-query',
    title: 'Exact selection expressed as a one-row list',
    replacement:
        'Use generated byId/require or a generated exact lookup when an '
        'unconditional key proves singularity; otherwise declare a safe '
        'conditional lookup instead of choosing the first row.',
  ),
  ConformanceRule(
    id: 'repeated-current-owner',
    title: 'Repeated authenticated owner argument',
    replacement:
        'Use the generated <Entity>List.owned(entityGraph) constructor.',
  ),
  ConformanceRule(
    id: 'mutable-persisted-field',
    title: 'Mutable persisted entity field',
    replacement:
        'Declare the field abstract final and mutate it through an awaited '
        'generated draft or semantic action.',
  ),
  ConformanceRule(
    id: 'manual-capability-member',
    title: 'Manually authored generated capability member',
    replacement:
        'Keep only the recognized capability interface; let Nodus generate '
        'its fields, actions, indexes, persistence, and synchronization.',
  ),
  ConformanceRule(
    id: 'sole-mutation-transaction',
    title: 'Transaction wrapping one generated mutation',
    replacement:
        'Call the generated mutation directly. Keep a transaction only for '
        'one real multi-entity aggregate invariant.',
  ),
  ConformanceRule(
    id: 'graph-forwarding-wrapper',
    title: 'No-op graph forwarding wrapper',
    replacement:
        'Call the generated set, list, lookup, entity, or relationship '
        'receiver directly and delete the forwarding method.',
  ),
  ConformanceRule(
    id: 'legacy-item-snapshots',
    title: 'Legacy itemSnapshots adapter',
    replacement:
        'Observe the generated query directly or use one lease-scoped '
        'generated read for imperative work.',
  ),
  ConformanceRule(
    id: 'unbounded-use-all',
    title: 'Complete read of an unbounded entity selection',
    replacement:
        'Use a bounded/indexed generated query with paging, or declare a '
        'query-owned bulk action or durable process.',
  ),
  ConformanceRule(
    id: 'client-bulk-loop',
    title: 'Client mutation loop over an unbounded selection',
    replacement:
        'Declare one query-owned semantic bulk action or durable process; '
        'Nodus must own paging, atomicity, retry, and recovery.',
  ),
  ConformanceRule(
    id: 'raw-identity-bridge',
    title: 'Raw identity compatibility bridge',
    replacement:
        'Keep LocalId<Entity> nominal through domain and presentation code; '
        'convert only at a typed external boundary.',
  ),
  ConformanceRule(
    id: 'persistence-success-log',
    title: 'Feature-level persistence or synchronization success log',
    replacement:
        'Remove the generic success log. Nodus owns persistence, queue, and '
        'synchronization diagnostics at their runtime boundaries.',
  ),
  ConformanceRule(
    id: 'structured-persisted-field',
    title: 'JSON or collection-shaped persisted entity field',
    replacement:
        'Normalize structured state into entities and relationships or use '
        'a native flattened typed variant.',
  ),
  ConformanceRule(
    id: 'ambient-domain-clock',
    title: 'Ambient wall clock in a domain or aggregate boundary',
    replacement:
        'Use entityGraph.nowUtc() at the mutation boundary or require an '
        'explicit time in the pure domain operation.',
  ),
];

final class ConformanceFinding {
  const ConformanceFinding({
    required this.rule,
    required this.path,
    required this.line,
    required this.column,
    required this.evidence,
    required this.replacement,
    this.entity,
  });

  final String rule;
  final String path;
  final int line;
  final int column;
  final String evidence;
  final String replacement;
  final String? entity;

  Map<String, Object?> toJson() => {
    'rule': rule,
    'path': path,
    'line': line,
    'column': column,
    'evidence': evidence,
    'replacement': replacement,
    if (entity != null) 'entity': entity,
  };
}

final class ConformanceInventoryReport {
  const ConformanceInventoryReport({
    required this.graph,
    required this.findings,
  });

  final String graph;
  final List<ConformanceFinding> findings;

  String toMarkdown() {
    final byRule = <String, List<ConformanceFinding>>{
      for (final rule in nodusConformanceRules) rule.id: [],
    };
    for (final finding in findings) {
      byRule[finding.rule]!.add(finding);
    }
    final output = StringBuffer()
      ..writeln('# Nodus semantic conformance inventory')
      ..writeln()
      ..writeln('<!-- GENERATED by `dart run nodus inventory --write`. -->')
      ..writeln()
      ..writeln(
        'This deterministic report combines the resolved `$graph` graph '
        'metadata with analyzer ASTs. Findings are migration evidence, not '
        'architecture exceptions.',
      )
      ..writeln()
      ..writeln('## Summary')
      ..writeln()
      ..writeln('| Classification | Findings |')
      ..writeln('| --- | ---: |');
    for (final rule in nodusConformanceRules) {
      output.writeln(
        '| `${rule.id}` — ${_markdown(rule.title)} | '
        '${byRule[rule.id]!.length} |',
      );
    }
    output
      ..writeln()
      ..writeln('Total findings: **${findings.length}**.')
      ..writeln()
      ..writeln('## Evidence');
    if (findings.isEmpty) {
      output
        ..writeln()
        ..writeln('No semantic conformance findings.');
      return output.toString();
    }
    for (final rule in nodusConformanceRules) {
      final entries = byRule[rule.id]!;
      if (entries.isEmpty) continue;
      output
        ..writeln()
        ..writeln('### ${rule.title} (`${rule.id}`)')
        ..writeln()
        ..writeln('| Location | Entity | Evidence | Generated replacement |')
        ..writeln('| --- | --- | --- | --- |');
      for (final finding in entries) {
        output.writeln(
          '| `${_markdown(finding.path)}:${finding.line}:${finding.column}` '
          '| ${_markdown(finding.entity ?? '—')} '
          '| `${_markdown(finding.evidence)}` '
          '| ${_markdown(finding.replacement)} |',
        );
      }
    }
    return output.toString();
  }

  String toPrettyJson() {
    const encoder = JsonEncoder.withIndent('  ');
    final counts = {
      for (final rule in nodusConformanceRules)
        rule.id: findings.where((finding) => finding.rule == rule.id).length,
    };
    return '${encoder.convert({
      'version': 1,
      'graph': graph,
      'rules': [
        for (final rule in nodusConformanceRules) {'id': rule.id, 'title': rule.title, 'count': counts[rule.id]},
      ],
      'findings': [for (final finding in findings) finding.toJson()],
    })}\n';
  }
}

final class NodusConformanceInventory {
  NodusConformanceInventory({required Directory root}) : root = root.absolute;

  final Directory root;

  ConformanceInventoryReport scan() {
    final metadata = _GraphMetadata.read(
      File(
        path.join(root.path, 'lib', 'src', 'generated', 'nodus.explain.g.json'),
      ),
    );
    final findings = <ConformanceFinding>[];
    final files = _sourceFiles();
    for (final file in files) {
      final source = file.readAsStringSync();
      if (_isGeneratedSource(file, source)) continue;
      final parsed = parseString(
        content: source,
        path: file.path,
        throwIfDiagnostics: false,
      );
      final relative = path.relative(file.path, from: root.path);
      final context = _SourceContext(
        relativePath: relative,
        source: source,
        lineInfo: parsed.lineInfo,
      );
      parsed.unit.accept(
        _ConformanceVisitor(
          metadata: metadata,
          context: context,
          addFinding: findings.add,
        ),
      );
    }
    final ruleOrder = {
      for (var index = 0; index < nodusConformanceRules.length; index++)
        nodusConformanceRules[index].id: index,
    };
    findings.sort((left, right) {
      final byRule = ruleOrder[left.rule]!.compareTo(ruleOrder[right.rule]!);
      if (byRule != 0) return byRule;
      final byPath = left.path.compareTo(right.path);
      if (byPath != 0) return byPath;
      final byLine = left.line.compareTo(right.line);
      if (byLine != 0) return byLine;
      return left.column.compareTo(right.column);
    });
    return ConformanceInventoryReport(
      graph: metadata.graphName,
      findings: List.unmodifiable(findings),
    );
  }

  List<File> _sourceFiles() {
    final sourceRoot = Directory(path.join(root.path, 'lib'));
    if (!sourceRoot.existsSync()) return const [];
    final files = sourceRoot
        .listSync(recursive: true, followLinks: false)
        .whereType<File>()
        .where((file) => file.path.endsWith('.dart'))
        .toList(growable: false);
    files.sort((left, right) => left.path.compareTo(right.path));
    return files;
  }

  bool _isGeneratedSource(File file, String source) {
    final relative = path.relative(file.path, from: root.path);
    return relative.contains(
          '${path.separator}src${path.separator}generated',
        ) ||
        relative.endsWith('.g.dart') ||
        relative.endsWith('.freezed.dart') ||
        relative.endsWith('.entity.g.dart') ||
        source.startsWith('// GENERATED CODE');
  }
}

final class _GraphMetadata {
  const _GraphMetadata({required this.graphName, required this.entities});

  final String graphName;
  final List<_EntityMetadata> entities;

  Map<String, _EntityMetadata> get byName => {
    for (final entity in entities) entity.name: entity,
  };

  Map<String, _EntityMetadata> get byListName => {
    for (final entity in entities) entity.listName: entity,
  };

  static _GraphMetadata read(File file) {
    if (!file.existsSync()) {
      throw FormatException(
        'Missing generated graph explanation at ${file.path}.',
      );
    }
    final decoded = jsonDecode(file.readAsStringSync());
    if (decoded is! Map<String, Object?>) {
      throw FormatException('Invalid graph explanation at ${file.path}.');
    }
    final rawEntities = decoded['entities'];
    if (rawEntities is! List<Object?>) {
      throw FormatException('Graph explanation has no entity list.');
    }
    final entities = <_EntityMetadata>[];
    for (final rawEntity in rawEntities) {
      if (rawEntity is! Map<String, Object?>) {
        throw FormatException('Invalid entity graph explanation entry.');
      }
      final generated = rawEntity['generatedApi'];
      if (generated is! Map<String, Object?>) {
        throw FormatException(
          'Entity ${rawEntity['name']} has no generated API explanation.',
        );
      }
      final table = rawEntity['table']! as String;
      entities.add(
        _EntityMetadata(
          name: rawEntity['name']! as String,
          source: rawEntity['source']! as String,
          ownership: rawEntity['ownership']! as String,
          unbounded: rawEntity['cardinality'] == 'unbounded',
          setAccessor:
              generated['setAccessor'] as String? ?? _lowerCamel(table),
          listName: generated['list']! as String,
          capabilities: _enabledCapabilities(rawEntity['capabilities']),
          actionNames: {
            for (final action in (rawEntity['actions']! as List<Object?>))
              (action! as Map<String, Object?>)['name']! as String,
          },
        ),
      );
    }
    return _GraphMetadata(
      graphName: decoded['graph']! as String,
      entities: List.unmodifiable(entities),
    );
  }

  static Set<String> _enabledCapabilities(Object? value) {
    if (value is! Map<String, Object?>) return const {};
    return {
      for (final entry in value.entries)
        if (entry.value == true) entry.key,
    };
  }
}

final class _EntityMetadata {
  const _EntityMetadata({
    required this.name,
    required this.source,
    required this.ownership,
    required this.unbounded,
    required this.setAccessor,
    required this.listName,
    required this.capabilities,
    required this.actionNames,
  });

  final String name;
  final String source;
  final String ownership;
  final bool unbounded;
  final String setAccessor;
  final String listName;
  final Set<String> capabilities;
  final Set<String> actionNames;
}

final class _SourceContext {
  const _SourceContext({
    required this.relativePath,
    required this.source,
    required this.lineInfo,
  });

  final String relativePath;
  final String source;
  final LineInfo lineInfo;
}

final class _ConformanceVisitor extends RecursiveAstVisitor<void> {
  _ConformanceVisitor({
    required this.metadata,
    required this.context,
    required void Function(ConformanceFinding finding) addFinding,
  }) : _addFinding = addFinding,
       _entitiesByName = metadata.byName,
       _entitiesByListName = metadata.byListName,
       _mutationNames = {
         ..._conventionalMutationNames,
         for (final entity in metadata.entities) ...entity.actionNames,
       };

  final _GraphMetadata metadata;
  final _SourceContext context;
  final void Function(ConformanceFinding finding) _addFinding;
  final Map<String, _EntityMetadata> _entitiesByName;
  final Map<String, _EntityMetadata> _entitiesByListName;
  final Set<String> _mutationNames;
  final Set<String> _findingKeys = {};

  _EntityMetadata? _currentEntity;
  String? _currentExtensionType;
  Map<String, Set<_EntityMetadata>> _localBindings = const {};

  @override
  void visitClassDeclaration(ClassDeclaration node) {
    final previous = _currentEntity;
    final className = node.namePart.typeName.lexeme;
    _currentEntity = _entitiesByName[className];
    if (_currentEntity != null || _hasAnnotation(node.metadata, 'Entity')) {
      _inspectEntityDeclaration(node, _currentEntity);
    }
    super.visitClassDeclaration(node);
    _currentEntity = previous;
  }

  @override
  void visitExtensionDeclaration(ExtensionDeclaration node) {
    final previous = _currentExtensionType;
    _currentExtensionType = node.onClause?.extendedType.toSource();
    super.visitExtensionDeclaration(node);
    _currentExtensionType = previous;
  }

  @override
  void visitMethodDeclaration(MethodDeclaration node) {
    final previous = _localBindings;
    _localBindings = _collectLocalBindings(node.body, previous);
    _inspectRawIdentityGetter(node);
    _inspectGraphForwarder(node);
    super.visitMethodDeclaration(node);
    _localBindings = previous;
  }

  @override
  void visitFunctionDeclaration(FunctionDeclaration node) {
    final previous = _localBindings;
    _localBindings = _collectLocalBindings(
      node.functionExpression.body,
      previous,
    );
    super.visitFunctionDeclaration(node);
    _localBindings = previous;
  }

  @override
  void visitArgumentList(ArgumentList node) {
    for (final argument in node.arguments) {
      if (RegExp(r'^pageSize\s*:\s*1$').hasMatch(argument.toSource())) {
        _finding(
          'exact-one-query',
          node.parent ?? node,
          entity: _singleEntityFromSource(node.parent?.toSource() ?? ''),
        );
      }
    }
    super.visitArgumentList(node);
  }

  @override
  void visitInstanceCreationExpression(InstanceCreationExpression node) {
    final constructor = node.constructorName.name?.name;
    if (constructor == 'forOwner') {
      _inspectCurrentOwner(
        node,
        node.constructorName.type.toSource(),
        node.argumentList,
      );
    }
    super.visitInstanceCreationExpression(node);
  }

  @override
  void visitMethodInvocation(MethodInvocation node) {
    final name = node.methodName.name;
    if (name == 'forOwner') {
      _inspectCurrentOwner(node, node.target?.toSource(), node.argumentList);
    }
    if (name == 'transaction') _inspectTransaction(node);
    if (name == 'useAll') _inspectUseAll(node);
    if (name == 'now' && node.target?.toSource() == 'DateTime') {
      final domainPath = context.relativePath.contains('/domain/');
      final aggregateBoundary =
          _currentEntity != null ||
          _currentExtensionType == metadata.graphName ||
          _entitiesByName.containsKey(_currentExtensionType);
      if (domainPath || aggregateBoundary) {
        _finding('ambient-domain-clock', node, entity: _currentEntity);
      }
    }
    _inspectSuccessLog(node);
    super.visitMethodInvocation(node);
  }

  @override
  void visitSimpleIdentifier(SimpleIdentifier node) {
    if (node.name == 'itemSnapshots' &&
        (node.parent is PropertyAccess || node.parent is PrefixedIdentifier)) {
      _finding('legacy-item-snapshots', node, entity: _currentEntity);
    }
    super.visitSimpleIdentifier(node);
  }

  void _inspectEntityDeclaration(
    ClassDeclaration node,
    _EntityMetadata? entity,
  ) {
    final interfaces = {
      for (final type
          in node.implementsClause?.interfaces ?? const <NamedType>[])
        type.toSource().split('<').first,
    };
    final repeatedMembers = <String>{};
    for (final member in node.body.members) {
      if (member is FieldDeclaration) {
        if (member.isStatic) continue;
        final type = member.fields.type?.toSource() ?? '';
        for (final variable in member.fields.variables) {
          if (!member.fields.isFinal && !member.fields.isConst) {
            _finding('mutable-persisted-field', variable, entity: entity);
          }
          if (_isStructuredType(type)) {
            _finding('structured-persisted-field', variable, entity: entity);
          }
          repeatedMembers.add(variable.name.lexeme);
        }
      } else if (member is MethodDeclaration) {
        repeatedMembers.add(member.name.lexeme);
      }
    }
    for (final interface in interfaces) {
      final ownedMembers = _capabilityMembers[interface];
      if (ownedMembers == null) continue;
      for (final name in repeatedMembers.intersection(ownedMembers)) {
        final member = node.body.members.firstWhere(
          (candidate) => _memberNames(candidate).contains(name),
        );
        _finding(
          'manual-capability-member',
          member,
          entity: entity,
          replacement:
              'Remove `$name`; `$interface` supplies the complete generated '
              'capability.',
        );
      }
    }
  }

  void _inspectRawIdentityGetter(MethodDeclaration node) {
    if (!node.isGetter ||
        node.returnType?.toSource().startsWith('String') != true) {
      return;
    }
    final expression = _singleExpression(node.body)?.toSource();
    if (expression == null ||
        !RegExp(r'\b(?:\w+Id|\w+\.id)\.value\b').hasMatch(expression)) {
      return;
    }
    _finding('raw-identity-bridge', node, entity: _currentEntity);
  }

  void _inspectGraphForwarder(MethodDeclaration node) {
    if (_currentExtensionType != metadata.graphName || node.isGetter) return;
    final expression = _singleExpression(node.body);
    if (expression == null || !_isForwardingExpression(node, expression)) {
      return;
    }
    _finding(
      'graph-forwarding-wrapper',
      node,
      entity: _singleEntityFromSource(expression.toSource()),
    );
  }

  bool _isForwardingExpression(
    MethodDeclaration method,
    Expression expression,
  ) {
    final parameters = {
      for (final parameter
          in method.parameters?.parameters ?? const <FormalParameter>[])
        if (parameter.name != null) parameter.name!.lexeme,
    };
    final arguments = switch (expression) {
      MethodInvocation invocation => invocation.argumentList.arguments,
      InstanceCreationExpression creation => creation.argumentList.arguments,
      _ => null,
    };
    if (arguments == null) return false;
    for (final argument in arguments) {
      final source = _argumentValueSource(argument.toSource());
      if (!parameters.contains(source) &&
          source != 'this' &&
          source != 'accountId' &&
          source != 'entityGraph' &&
          !source.endsWith('.accountId')) {
        return false;
      }
    }
    if (expression is InstanceCreationExpression) {
      final type = expression.constructorName.type.toSource();
      return type.endsWith('List') || type.endsWith('Lookup');
    }
    final invocation = expression as MethodInvocation;
    final target = invocation.target?.toSource() ?? '';
    return parameters.contains(invocation.methodName.name) ||
        _mutationNames.contains(invocation.methodName.name) ||
        invocation.methodName.name.startsWith('lookup') ||
        invocation.methodName.name.startsWith('require') ||
        invocation.methodName.name.startsWith('by') ||
        _entitiesFromSource(target).isNotEmpty ||
        target.endsWith('List') ||
        target.endsWith('Lookup');
  }

  void _inspectCurrentOwner(
    AstNode node,
    String? listSource,
    ArgumentList arguments,
  ) {
    final entity = listSource == null
        ? null
        : _entitiesByListName[listSource.split('<').first];
    if (entity == null || entity.ownership != 'separate') return;
    final positional = [
      for (final argument in arguments.arguments)
        if (!_isNamedArgumentSource(argument.toSource())) argument,
    ];
    if (positional.length < 2) return;
    final graph = positional.first.toSource();
    final owner = positional[1].toSource();
    final isCurrentOwner =
        owner == 'accountId' ||
        owner == '$graph.accountId' ||
        (graph == 'this' && owner == 'this.accountId');
    if (!isCurrentOwner) return;
    _finding(
      'repeated-current-owner',
      node,
      entity: entity,
      replacement: '${entity.listName}.owned($graph)',
    );
  }

  void _inspectTransaction(MethodInvocation node) {
    final callback = node.argumentList.arguments
        .whereType<FunctionExpression>()
        .firstOrNull;
    if (callback == null) return;
    final expression = _singleExpression(callback.body);
    if (expression is! MethodInvocation || !_isMutation(expression)) return;
    _finding(
      'sole-mutation-transaction',
      node,
      entity: _singleEntityFromSource(expression.toSource()),
    );
  }

  void _inspectUseAll(MethodInvocation node) {
    final entities = _entitiesFromExpression(node.target);
    final unbounded = entities.where((entity) => entity.unbounded).toSet();
    if (unbounded.isEmpty) return;
    final entity = unbounded.length == 1 ? unbounded.single : null;
    _finding('unbounded-use-all', node, entity: entity);
    final callback = node.argumentList.arguments
        .whereType<FunctionExpression>()
        .firstOrNull;
    if (callback == null) return;
    final bulk = _MutationLoopFinder(_isMutation)..search(callback.body);
    for (final loop in bulk.loops) {
      _finding('client-bulk-loop', loop, entity: entity);
    }
  }

  void _inspectSuccessLog(MethodInvocation node) {
    if (!const {
      'debug',
      'fine',
      'finer',
      'finest',
      'info',
      'trace',
    }.contains(node.methodName.name)) {
      return;
    }
    final target = (node.target?.toSource() ?? '').toLowerCase();
    if (!target.contains('log')) return;
    final message = node.argumentList.arguments
        .whereType<StringLiteral>()
        .map((literal) => literal.stringValue)
        .whereType<String>()
        .join(' ')
        .toLowerCase();
    if (message.isEmpty ||
        !_containsAny(message, _successWords) ||
        !_containsAny(message, _persistenceWords)) {
      return;
    }
    final featurePath =
        context.relativePath.contains('/features/') ||
        context.relativePath.contains('/domain/') ||
        context.relativePath.contains('/application/');
    if (featurePath) {
      _finding('persistence-success-log', node, entity: _currentEntity);
    }
  }

  Map<String, Set<_EntityMetadata>> _collectLocalBindings(
    FunctionBody body,
    Map<String, Set<_EntityMetadata>> inherited,
  ) {
    final declarations = <VariableDeclaration>[];
    body.accept(_VariableCollector(declarations.add));
    final bindings = <String, Set<_EntityMetadata>>{
      for (final entry in inherited.entries) entry.key: {...entry.value},
    };
    for (var pass = 0; pass < 2; pass++) {
      for (final declaration in declarations) {
        final initializer = declaration.initializer;
        if (initializer == null) continue;
        final entities = _entitiesFromExpression(
          initializer,
          bindings: bindings,
        );
        if (entities.isNotEmpty) bindings[declaration.name.lexeme] = entities;
      }
    }
    return bindings;
  }

  Set<_EntityMetadata> _entitiesFromExpression(
    Expression? expression, {
    Map<String, Set<_EntityMetadata>>? bindings,
  }) {
    if (expression == null) return const {};
    final activeBindings = bindings ?? _localBindings;
    final result = _entitiesFromSource(expression.toSource());
    final identifiers = <String>[];
    expression.accept(_IdentifierCollector(identifiers.add));
    for (final identifier in identifiers) {
      result.addAll(activeBindings[identifier] ?? const {});
    }
    return result;
  }

  Set<_EntityMetadata> _entitiesFromSource(String source) {
    final result = <_EntityMetadata>{};
    for (final entity in metadata.entities) {
      if (RegExp('\\b${RegExp.escape(entity.listName)}\\b').hasMatch(source) ||
          RegExp(
            '\\.${RegExp.escape(entity.setAccessor)}\\b',
          ).hasMatch(source)) {
        result.add(entity);
      }
    }
    return result;
  }

  _EntityMetadata? _singleEntityFromSource(String source) {
    final entities = _entitiesFromSource(source);
    return entities.length == 1 ? entities.single : null;
  }

  bool _isMutation(MethodInvocation invocation) {
    final name = invocation.methodName.name;
    return _mutationNames.contains(name) ||
        _mutationPrefixes.any(name.startsWith);
  }

  void _finding(
    String rule,
    AstNode node, {
    _EntityMetadata? entity,
    String? replacement,
  }) {
    final location = context.lineInfo.getLocation(node.offset);
    final key = '$rule:${context.relativePath}:${node.offset}';
    if (!_findingKeys.add(key)) return;
    final descriptor = nodusConformanceRules.singleWhere(
      (candidate) => candidate.id == rule,
    );
    _addFinding(
      ConformanceFinding(
        rule: rule,
        path: context.relativePath,
        line: location.lineNumber,
        column: location.columnNumber,
        evidence: _evidence(node.toSource()),
        replacement: replacement ?? descriptor.replacement,
        entity: entity?.name ?? _currentEntity?.name,
      ),
    );
  }
}

final class _VariableCollector extends RecursiveAstVisitor<void> {
  _VariableCollector(this.add);

  final void Function(VariableDeclaration declaration) add;

  @override
  void visitVariableDeclaration(VariableDeclaration node) {
    add(node);
    super.visitVariableDeclaration(node);
  }
}

final class _IdentifierCollector extends RecursiveAstVisitor<void> {
  _IdentifierCollector(this.add);

  final void Function(String identifier) add;

  @override
  void visitSimpleIdentifier(SimpleIdentifier node) {
    add(node.name);
    super.visitSimpleIdentifier(node);
  }
}

final class _MutationLoopFinder extends RecursiveAstVisitor<void> {
  _MutationLoopFinder(this.isMutation);

  final bool Function(MethodInvocation invocation) isMutation;
  final List<AstNode> loops = [];

  void search(AstNode node) => node.accept(this);

  @override
  void visitForStatement(ForStatement node) {
    if (_containsMutation(node.body)) loops.add(node);
    super.visitForStatement(node);
  }

  @override
  void visitMethodInvocation(MethodInvocation node) {
    if (const {'forEach', 'map'}.contains(node.methodName.name) &&
        node.argumentList.arguments.whereType<FunctionExpression>().any(
          (callback) => _containsMutation(callback.body),
        )) {
      loops.add(node);
    }
    super.visitMethodInvocation(node);
  }

  bool _containsMutation(AstNode node) {
    final finder = _MutationFinder(isMutation);
    node.accept(finder);
    return finder.found;
  }
}

final class _MutationFinder extends RecursiveAstVisitor<void> {
  _MutationFinder(this.isMutation);

  final bool Function(MethodInvocation invocation) isMutation;
  bool found = false;

  @override
  void visitMethodInvocation(MethodInvocation node) {
    if (isMutation(node)) found = true;
    if (!found) super.visitMethodInvocation(node);
  }
}

Expression? _singleExpression(FunctionBody body) {
  Expression? expression;
  if (body is ExpressionFunctionBody) {
    expression = body.expression;
  } else if (body is BlockFunctionBody && body.block.statements.length == 1) {
    final statement = body.block.statements.single;
    expression = switch (statement) {
      ExpressionStatement value => value.expression,
      ReturnStatement value => value.expression,
      _ => null,
    };
  }
  while (expression is AwaitExpression) {
    expression = expression.expression;
  }
  return expression;
}

bool _hasAnnotation(NodeList<Annotation> metadata, String name) => metadata.any(
  (annotation) => annotation.name.toSource().split('.').last == name,
);

bool _isStructuredType(String type) {
  final base = type.replaceFirst(RegExp(r'\?$'), '').split('<').first;
  return const {
    'List',
    'Set',
    'Map',
    'Iterable',
    'JsonMap',
    'Object',
    'dynamic',
  }.contains(base);
}

Set<String> _memberNames(ClassMember member) => switch (member) {
  FieldDeclaration field => {
    for (final variable in field.fields.variables) variable.name.lexeme,
  },
  MethodDeclaration method => {method.name.lexeme},
  _ => const {},
};

String _evidence(String source) {
  final compact = source.replaceAll(RegExp(r'\s+'), ' ').trim();
  if (compact.length <= 180) return compact;
  return '${compact.substring(0, 177)}...';
}

String _markdown(String source) =>
    source.replaceAll('|', r'\|').replaceAll('`', "'").replaceAll('\n', ' ');

String _lowerCamel(String snakeCase) {
  final parts = snakeCase.split('_');
  return parts.first +
      parts
          .skip(1)
          .map((part) => '${part[0].toUpperCase()}${part.substring(1)}')
          .join();
}

bool _containsAny(String source, Set<String> candidates) =>
    candidates.any(source.contains);

bool _isNamedArgumentSource(String source) =>
    RegExp(r'^[a-zA-Z_$][a-zA-Z0-9_$]*\s*:').hasMatch(source);

String _argumentValueSource(String source) {
  if (!_isNamedArgumentSource(source)) return source;
  return source.substring(source.indexOf(':') + 1).trim();
}

const _capabilityMembers = <String, Set<String>>{
  'Archivable': {'archivedAt', 'archive', 'unarchive'},
  'SoftDeletable': {'deletedAt', 'remove', 'restore'},
  'Activatable': {'active', 'activate', 'deactivate'},
  'Collaborative': {'setCollaborator'},
  'Ordered': {'orderRank', 'sortOrder', 'moveTo'},
};

const _conventionalMutationNames = <String>{
  'activate',
  'archive',
  'create',
  'createFirst',
  'deactivate',
  'link',
  'moveAfter',
  'moveBefore',
  'remove',
  'replace',
  'restore',
  'save',
  'setCollaborator',
  'unarchive',
  'unlink',
};

const _mutationPrefixes = <String>{
  'apply',
  'archive',
  'complete',
  'configure',
  'create',
  'deactivate',
  'delete',
  'edit',
  'link',
  'mark',
  'move',
  'record',
  'remove',
  'replace',
  'restore',
  'save',
  'set',
  'start',
  'stop',
  'unarchive',
  'unlink',
  'update',
};

const _successWords = <String>{
  'complete',
  'created',
  'deleted',
  'persisted',
  'saved',
  'success',
  'synced',
  'updated',
};

const _persistenceWords = <String>{
  'archive',
  'create',
  'delete',
  'entity',
  'persist',
  'queue',
  'record',
  'remove',
  'save',
  'sync',
  'update',
};
