import 'dart:io';

import '../configuration.dart';
import 'migration_generator.dart';

const nodusInitUsage = '''Usage: dart run nodus init --target NAME

Discovers every @Entity in the package and creates the tool-owned graph setup.

Options:
  --target NAME  Default remote target, for example `supabase`.
  -h, --help     Show this help.
''';

final class NodusInitOptions {
  const NodusInitOptions({required this.target, this.showHelp = false});

  final String? target;
  final bool showHelp;
}

NodusInitOptions parseInitOptions(List<String> arguments) {
  if (arguments.length == 1 &&
      (arguments.single == '--help' || arguments.single == '-h')) {
    return const NodusInitOptions(target: null, showHelp: true);
  }
  String? target;
  for (var index = 0; index < arguments.length; index++) {
    switch (arguments[index]) {
      case '--target':
        if (target != null) {
          throw const NodusToolUsageException(
            '--target may be provided only once.',
          );
        }
        if (++index >= arguments.length) {
          throw const NodusToolUsageException(
            '--target requires a target name.',
          );
        }
        target = arguments[index];
      case '--help' || '-h':
        throw const NodusToolUsageException(
          '--help must be used without other options.',
        );
      default:
        throw NodusToolUsageException(
          'Unknown init argument: ${arguments[index]}',
        );
    }
  }
  if (target == null) {
    throw const NodusToolUsageException('init requires --target NAME.');
  }
  if (!isValidNodusTargetName(target)) {
    throw NodusToolUsageException(
      'Target "$target" must use a non-reserved lower_snake_case name.',
    );
  }
  return NodusInitOptions(target: target);
}

final class NodusInitializer {
  NodusInitializer({
    required Directory root,
    void Function(String message)? report,
  }) : root = root.absolute,
       _report = report ?? stdout.writeln;

  final Directory root;
  final void Function(String message) _report;

  NodusLock initialize(NodusInitOptions options) {
    final target = options.target;
    if (options.showHelp || target == null) {
      throw const NodusToolUsageException(
        'Cannot initialize without a target.',
      );
    }
    final pubspec = File(_path('pubspec.yaml'));
    final library = Directory(_path('lib'));
    if (!pubspec.existsSync() || !library.existsSync()) {
      throw const NodusToolUsageException(
        'Run nodus init from the root of a Dart or Flutter application.',
      );
    }
    final lockFile = File(_path('nodus.lock'));
    final packageName = _readPackageName(pubspec.readAsStringSync());
    if (lockFile.existsSync()) {
      final existing = NodusLock.decode(lockFile.readAsStringSync());
      if (existing.packageName != packageName ||
          existing.targets.length != 1 ||
          existing.defaultTarget != target) {
        throw const NodusToolUsageException(
          'Existing nodus.lock has different package or target settings. '
          'Change irreducible graph configuration through a reviewed '
          'nodus.yaml migration.',
        );
      }
      final buildChanged = _writeDriftBuildConfiguration(packageName);
      _report('Kept existing nodus.lock');
      _report(
        '${buildChanged ? 'Updated' : 'Kept'} generated Drift database '
        'configuration.',
      );
      return existing;
    }
    final graphName = _pascalCase(packageName);
    final lock = NodusLock.decode(
      NodusLock(
        packageName: packageName,
        graphName: graphName,
        schemaVersion: 1,
        schemaFingerprint: null,
        targets: [target],
        defaultTarget: target,
      ).encode(),
    );
    _writeDriftBuildConfiguration(packageName);
    lockFile.writeAsStringSync(lock.encode());
    _report('Created nodus.lock');
    _report('Configured generated Drift database `$packageName`.');
    return lock;
  }

  bool _writeDriftBuildConfiguration(String packageName) {
    final buildFile = File(_path('build.yaml'));
    if (buildFile.existsSync()) {
      final source = buildFile.readAsStringSync();
      if (!source.startsWith('# GENERATED BY NODUS.')) {
        throw const NodusToolUsageException(
          'build.yaml already contains handwritten configuration. Move the '
          'irreducible settings to nodus.yaml before running init; Nodus owns '
          'the standard Drift build configuration.',
        );
      }
    }
    return writeIfChanged(buildFile, '''# GENERATED BY NODUS. DO NOT EDIT.
targets:
  \$default:
    sources:
      - lib/**
      - test/**
      - nodus.lock
      - \$package\$
    builders:
      drift_dev:drift_dev:
        enabled: false
      drift_dev:not_shared:
        generate_for:
          - lib/src/generated/nodus.runtime.g.dart
        options:
          databases:
            $packageName: lib/src/generated/nodus.runtime.g.dart
''');
  }

  String _path(String relative) =>
      '${root.path}${Platform.pathSeparator}$relative';
}

String _readPackageName(String pubspec) {
  final match = RegExp(
    r'^name:\s*([a-z][a-z0-9_]*)\s*$',
    multiLine: true,
  ).firstMatch(pubspec);
  if (match == null) {
    throw const NodusToolUsageException(
      'pubspec.yaml must declare one lower_snake_case package name.',
    );
  }
  return match.group(1)!;
}

String _pascalCase(String value) => value
    .split('_')
    .where((part) => part.isNotEmpty)
    .map((part) => '${part[0].toUpperCase()}${part.substring(1)}')
    .join();
